volumes:
  tracker-data:

services:
  tracker-web:
    image: quay.io/rajware/expensetracker-go:latest
    volumes:
      - tracker-data:/app/data
    ports:
      - "18080:8080"
    environment:
      - ET_HMAC_KEY=puxx
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: "${RANDOM_UID:-1000660000}:0"
    tmpfs:
      - /tmp
    restart: unless-stopped
