apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracker-postgres-pvc
  labels:
    app.kubernetes.io/name: expensetracker
    rajware.net/variation: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
