apiVersion: v1
kind: Service
metadata:
  name: tracker-postgres-db-svc
  labels:
    app.kubernetes.io/name: expensetracker
    rajware.net/variation: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: expensetracker
    rajware.net/variation: postgres
    app.kubernetes.io/component: backend
  ports:
    - name: postgres
      port: 5432
