apiVersion: v1
kind: Service
metadata:
  name: tracker-sqlite-svc
  labels:
    app.kubernetes.io/name: expensetracker
    rajware.net/variation: sqlite
spec:
  type: NodePort  # Change to ClusterIP if the cluster has an Ingress controller, or LoadBalancer
  selector:
    app.kubernetes.io/name: expensetracker
    rajware.net/variation: sqlite
    app.kubernetes.io/component: application
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000 # Remove if the cluster has an Ingress controller
