apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracker-sqlite-pvc
  labels:
    app.kubernetes.io/name: expensetracker
    rajware.net/variation: sqlite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
